version: '3.7'
services:
  web:
    build: ./django_data
    command: sh entrypoint.sh
    env_file:
      - ./django_data/django.env
    volumes:
      - .:/code
      - static_volume:/code/django_data/staticfiles
      - media_volume:/code/django_data/mediafiles
    expose:
      - 8000
    depends_on:
      - db
  db:
    image: postgres:11
    env_file:
      - ./postgres_data/postgres.env
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  nginx:
    build: ./nginx_data
    volumes:
      - static_volume:/code/django_data/staticfiles
      - media_volume:/code/django_data/mediafiles
    ports:
      - 80:80
    depends_on:
      - web
volumes:
  postgres_data:
  static_volume:
  media_volume:
